### ISSUE TITLE
What for a game is this?

### ISSUE THREAD

**Issue by PluginBOXone** [jasonwynn10/MurderMysteryPMMP#1]
What for a game is this? what do i have todo in this minigame?

**Comment by jasonwynn10** [comment]
https://www.youtube.com/watch?v=PY13XKoJzkA&feature=em-subs_digest

**Comment by PluginBOXone** [comment]
Oh this game I LOVE THIS xD Is it allready done or still in development?

**Comment by jasonwynn10** [comment]
It's still Work in Progress
